### ISSUE TITLE
Library name generation

### ISSUE THREAD

**Issue by roncoronimiguel** [usegalaxy-eu/ena-upload-cli#23]
the contents of Library Name (Experiment metadata) appear to be ignored and automatically generated by concatenating "library"_"Experiment Alias"_"Sample Alias"

**Comment by bedroesb** [comment]
This behavior does not seems to be done by the commandline tool since we read it out straight from the table as seen [here](                    https://github.com/usegalaxy-eu/ena-upload-cli/blob/1bac5d50eb9c18a549d18f16021ab08490b23ae7/ena_upload/templates/ENA_template_experiments.xml#L21). Can it be that this is done by the wrapper?

**Comment by bedroesb** [comment]
This issue will be moved to https://github.com/galaxyproject/tools-iuc/issues
